spring:
  application:
    name: baeldung-thymeleaf

  datasource:
    url: jdbc:mysql://localhost:3306/baeldung_thymeleaf_db
    username: root
    password: N3v3r4#Mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true