spring:
  datasource:
    url: jdbc:mysql://localhost:3306/readinglist_db?useSSl=false
    username: root
    password: N3v3r4#Mysql
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    
server:
  port: 8080 