amazon:
  amazonAssociateId: habuma-20

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/readinglist_db?useSSl=false
    username: root
    password: N3v3r4#Mysql
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    
  thymeleaf:
    cache: false
    
  main:
    banner-mode: off
    
logging:
  file:
    path: /var/logs/
    name: BookWorm.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
    
server:
  port: 8080 