spring:
    datasource:
        generate-unique-name: false
        name: tacocloud_db
#    security:
#        oauth2:
#            client:
#                registration:
#                    <oauth2 or openid provider name>:
#                        clientId: <client id>
#                        clientSecret: <client secret>
#                        scope: <comma-separated list of requestd scopes>
    
    thymeleaf:
        cache: false

