#spring:
#  security: 
#    user: 
#      name: azad
#      password: 1234 

spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/simple_bank_db
    username: root
    password: N3v3r4#Mysql
  jpa:
    show-sql: true
    properties:
      hibernate: 
        format_sql: true