spring:
  application:
    name: sbur-rest-demo

greeting:
  name: Sanjida
  coffee: ${greeting.name} is drinking Cafe Careza

droid:
  id: BB-8
  description: Small, rolling android. Probably doesn't drink coffee.

management:
  endpoints:
    web:
      exposure:
        include: env, info, health
    health:
      show-details: always 
