spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  thymeleaf:
    cache: false
  data:
    rest:
      base-path: /data-api
  artemis:
    host: artemis.tacocloud.com
    port: 8161
    user: admin
    password: admin
  jms:
    template:
      default-destination: tacocloud.order.queue
