spring:
  datasource:
    url: jdbc:mysql://localhost:3306/budget_db
    username: root
    password: N3v3r4#Mysql
  jpa:
    hibernate:
      ddl-auth: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
