spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/spring_vue_demo_db
    username: root
    password: N3v3r4#Mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080


